/**
 * Generated by com.customshow.codegen
 *
 */
package com.customshow.search.indexing.SearchQueryService{

import com.flashflexpro.as3lib.utils.RootContextModule;
import com.flashflexpro.as3lib.rpc.RpcSpringMvcPost;
import com.flashflexpro.as3lib.rpc.RpcService;


//@see com.customshow.search.indexing.SearchQueryService.tmpTypeRef
public class tmpTypeRef extends RpcService{
    public function tmpTypeRef( context:RootContextModule ){
        super( context );
    }


}}