/**
 * Generated by com.customshow.codegen
 *
 */
package com.customshow.solr.query.web.common{

import com.flashflexpro.as3lib.utils.RootContextModule;
import com.flashflexpro.as3lib.rpc.RpcSpringMvcPost;
import com.flashflexpro.as3lib.rpc.RpcService;


//@see com.customshow.solr.query.web.common.FacetQueryProperties
public class FacetQueryProperties extends RpcService{
    public function FacetQueryProperties( context:RootContextModule ){
        super( context );
    }

    public static const RPC_count:String = "count";
    public function count( result:Function, fault:Function  ):RpcSpringMvcPost{
        return createRpcPost( RPC_count, arguments );
    }

    public static const RPC_facetQuery:String = "facetQuery";
    public function facetQuery( result:Function, fault:Function, arg1:Number, arg2:Number, arg3:Object, arg4:String, arg5:Boolean ):RpcSpringMvcPost{
        return createRpcPost( RPC_facetQuery, arguments );
    }

    public static const RPC_suggest:String = "suggest";
    public function suggest( result:Function, fault:Function, arg1:String, arg2:int ):RpcSpringMvcPost{
        return createRpcPost( RPC_suggest, arguments );
    }
}}