/**
 * Generated by com.customshow.codegen
 *
 */
package com.customshow.awsS3Download{

import com.flashflexpro.as3lib.utils.RootContextModule;
import com.flashflexpro.as3lib.rpc.RpcSpringMvcPost;
import com.flashflexpro.as3lib.rpc.RpcService;


//@see com.customshow.awsS3Download.AwsS3DownloadService
public class AwsS3DownloadService extends RpcService{
    public function AwsS3DownloadService( context:RootContextModule ){
        super( context );
    }

    public static const RPC_signAll:String = "signAll";
    public function signAll( result:Function, fault:Function  ):RpcSpringMvcPost{
        return createRpcPost( RPC_signAll, arguments );
    }
}}