/**
 * Generated by com.customshow.gradle.codegen
 *
 */
package com.customshow.reporting.dto{

import mx.events.PropertyChangeEvent;
import com.customshow.reporting.dto.DtoReportingAbstract;

[Bindable]
[RemoteClass(alias="com.customshow.reporting.dto.DtoReportingActivity")]
public class DtoReportingActivity extends com.customshow.reporting.dto.DtoReportingAbstract {
    public function DtoReportingActivity(){
    }

    public var fromSlideIndexOfPres:Number;
    public var toSlideIndexOfPres:Number;
    public var pauseBeginOrEnd:Number;
    public var fromSlideRefId:Number;
    public var clientTime:Number;
    public var toSlideRefId:Number;
    public var recTimeStamp:Number;
    public var fromSlideName:String;
    public var toSlideName:String;
    public var pauseReason:String;
}
}