/**
 * Generated by com.customshow.gradle.codegen
 *
 */
package com.customshow.reporting.dto{

import mx.events.PropertyChangeEvent;
import flash.events.EventDispatcher;
import org.apache.flex.collections.ArrayList;

[Bindable]
[RemoteClass(alias="com.customshow.reporting.dto.DtoReportingInfoSlideColOwner")]
public class DtoReportingInfoSlideColOwner extends EventDispatcher {
    public function DtoReportingInfoSlideColOwner(){
    }

    public var ownerId:Number;
    public var ownerEmail:String;
    public var ownerFirstName:String;
    public var ownerLastName:String;
    public var ownerClientId:Number;
    public var ownerClientName:String;
    public var ownerGroupId:Number;
    public var ownerGroupName:String;
    public var ownerGroupIdPath:String;
    public var ownerGroupNamePath:Array;
    public var slideRefIds:Array;
    public var slideRefNames:Array;
    public var slideIsLibs:Array;
    public var slideOwnerEmails:Array;
    public var slideOwnerFirstNames:Array;
    public var slideOwnerLastNames:Array;
    public var slideIds:Array;
    public var slideNames:Array;
    public var slideOwnerIds:Array;
    public var slideCreateTimes:Array;
    public var slideModifiedTimes:Array;
    public var slideOwnerGroupIds:Array;
    public var slideOwnerGroupNames:Array;
    public var slideOwnerGroupIdPaths:Array;
    public var slideOwnerGroupNamePaths:ArrayList;
    public var slideOwnerClientIds:Array;
    public var slideOwnerClientNames:Array;
    public var lastUpdatedTime:Number;
    public var createdTime:Number;
}
}