/**
 * Generated by com.customshow.gradle.codegen
 *
 */
package com.customshow.reporting.dto{

import mx.events.PropertyChangeEvent;
import flash.events.EventDispatcher;

[Bindable]
[RemoteClass(alias="com.customshow.reporting.dto.DtoReportingAbstract")]
public class DtoReportingAbstract extends EventDispatcher {
    public function DtoReportingAbstract(){
    }

    public var uid:String;
    public var clientSessionId:String;
    public var showSessionId:String;
    public var flexClientId:String;
}
}