/**
 * Generated by com.customshow.gradle.codegen
 *
 */
package com.customshow.reporting.dto{

import mx.events.PropertyChangeEvent;
import com.customshow.reporting.dto.DtoReportingActivity;

[Bindable]
[RemoteClass(alias="com.customshow.reporting.dto.DtoReportingShowEnd")]
public class DtoReportingShowEnd extends com.customshow.reporting.dto.DtoReportingActivity {
    public function DtoReportingShowEnd(){
    }

    public var termination:Boolean;
}
}