/**
 * Generated by com.customshow.gradle.codegen
 *
 */
package com.customshow.reporting.dto{

import mx.events.PropertyChangeEvent;
import com.customshow.reporting.dto.DtoReportingInfoShow;
import com.customshow.reporting.dto.DtoReportingActivity;

[Bindable]
[RemoteClass(alias="com.customshow.reporting.dto.DtoReportingShowStart")]
public class DtoReportingShowStart extends com.customshow.reporting.dto.DtoReportingActivity {
    public function DtoReportingShowStart(){
    }

    public var userId:Number;
    public var userEmail:String;
    public var userClientId:Number;
    public var userClientName:String;
    public var userGroupId:Number;
    public var userGroupName:String;
    public var userGroupIdPath:String;
    public var userGroupNamePath:Array;
    public var flArch:String;
    public var flL:String;
    public var flOs:String;
    public var flRx:Number;
    public var flRy:Number;
    public var flV:String;
    public var flUrl:String;
    public var ipAddress:String;
    public var location:String;
    public var coordinate:Array;
    public var appType:String;
    public var appVersion:String;
    public var processingSource:int;
    public var showInfo:DtoReportingInfoShow;
    public var presInfos:Array;
}
}