/**
 * Generated by com.customshow.gradle.codegen
 *
 */
package com.customshow.reporting.dto{

import mx.events.PropertyChangeEvent;
import com.customshow.reporting.dto.DtoReportingInfoSlideColOwner;

[Bindable]
[RemoteClass(alias="com.customshow.reporting.dto.DtoReportingInfoShow")]
public class DtoReportingInfoShow extends com.customshow.reporting.dto.DtoReportingInfoSlideColOwner {
    public function DtoReportingInfoShow(){
    }

    public var lookupId:String;
    public var slidePositionOfPres:Array;
    public var slideShowName:String;
    public var slideShowId:Number;
    public var slideIndexOfPres:Array;
    public var slidePresIds:Array;
    public var slidePresNames:Array;
}
}