/**
 * Generated by com.customshow.gradle.codegen
 *
 */
package com.customshow.reporting.dto{

import mx.events.PropertyChangeEvent;
import com.customshow.reporting.dto.DtoReportingInfoSlideColOwner;

[Bindable]
[RemoteClass(alias="com.customshow.reporting.dto.DtoReportingInfoPres")]
public class DtoReportingInfoPres extends com.customshow.reporting.dto.DtoReportingInfoSlideColOwner {
    public function DtoReportingInfoPres(){
    }

    public var presentationName:String;
    public var presentationId:Number;
    public var slidePositions:Array;
}
}