/**
 * Generated by com.customshow.codegen
 *
 */
package com.customshow.search.indexing{

import mx.events.PropertyChangeEvent;
import com.flashflexpro.as3lib.data.PropertyDesc;
import flash.events.EventDispatcher;

[Bindable]
[RemoteClass(alias="com.customshow.search.indexing.ResourceLibraryItem")]
public class ResourceLibraryItem extends EventDispatcher {
    public function ResourceLibraryItem(){
    }

    private static var _allProperties:Vector.<PropertyDesc> = null;
    public static function get allProperties():Vector.<PropertyDesc>{
        if( _allProperties == null ){
            _allProperties = properties;
        }
        return _allProperties;
    }
    private static var _properties:Vector.<PropertyDesc> = null;
    public static function get properties():Vector.<PropertyDesc>{
        if( _properties == null ){
            _properties = new <PropertyDesc>[ PROP_DESC_targetUuid, 
                PROP_DESC_targetId, 
                PROP_DESC_folderId, 
                PROP_DESC_targetName, 
                PROP_DESC_isLib, 
                PROP_DESC_targetType, 
                PROP_DESC_ownerId, 
                PROP_DESC_ownerName, 
                PROP_DESC_ownerFirstName, 
                PROP_DESC_ownerLastName, 
                PROP_DESC_ownerUsername, 
                PROP_DESC_createdTime, 
                PROP_DESC_modifiedTime, 
                PROP_DESC_resourceWidth, 
                PROP_DESC_resourceHeight, 
                PROP_DESC_filesize, 
                PROP_DESC_orgFilename, 
                PROP_DESC_resourceDuration, 
                PROP_DESC_uuidPath, 
                PROP_DESC_namePath, 
                PROP_DESC_thumbnailWidth, 
                PROP_DESC_thumbnailHeight, 
                PROP_DESC_thumbnailFileName, 
                PROP_DESC_indexedTime
            ];
        }
        return _properties;
    }
    public static const PROP_DESC_targetUuid:PropertyDesc = new PropertyDesc( "targetUuid" );
    public var targetUuid:String;

    public static const PROP_DESC_targetId:PropertyDesc = new PropertyDesc( "targetId" );
    public var targetId:Number;

    public static const PROP_DESC_folderId:PropertyDesc = new PropertyDesc( "folderId" );
    public var folderId:Number;

    public static const PROP_DESC_targetName:PropertyDesc = new PropertyDesc( "targetName" );
    public var targetName:String;

    public static const PROP_DESC_isLib:PropertyDesc = new PropertyDesc( "isLib" );
    public var isLib:Boolean;

    public static const PROP_DESC_targetType:PropertyDesc = new PropertyDesc( "targetType" );
    public var targetType:String;

    public static const PROP_DESC_ownerId:PropertyDesc = new PropertyDesc( "ownerId" );
    public var ownerId:Number;

    public static const PROP_DESC_ownerName:PropertyDesc = new PropertyDesc( "ownerName" );
    public var ownerName:String;

    public static const PROP_DESC_ownerFirstName:PropertyDesc = new PropertyDesc( "ownerFirstName" );
    public var ownerFirstName:String;

    public static const PROP_DESC_ownerLastName:PropertyDesc = new PropertyDesc( "ownerLastName" );
    public var ownerLastName:String;

    public static const PROP_DESC_ownerUsername:PropertyDesc = new PropertyDesc( "ownerUsername" );
    public var ownerUsername:String;

    public static const PROP_DESC_createdTime:PropertyDesc = new PropertyDesc( "createdTime" );
    public var createdTime:Date;

    public static const PROP_DESC_modifiedTime:PropertyDesc = new PropertyDesc( "modifiedTime" );
    public var modifiedTime:Date;

    public static const PROP_DESC_resourceWidth:PropertyDesc = new PropertyDesc( "resourceWidth" );
    public var resourceWidth:Number;

    public static const PROP_DESC_resourceHeight:PropertyDesc = new PropertyDesc( "resourceHeight" );
    public var resourceHeight:Number;

    public static const PROP_DESC_filesize:PropertyDesc = new PropertyDesc( "filesize" );
    public var filesize:Number;

    public static const PROP_DESC_orgFilename:PropertyDesc = new PropertyDesc( "orgFilename" );
    public var orgFilename:String;

    public static const PROP_DESC_resourceDuration:PropertyDesc = new PropertyDesc( "resourceDuration" );
    public var resourceDuration:Number;

    public static const PROP_DESC_uuidPath:PropertyDesc = new PropertyDesc( "uuidPath" );
    public var uuidPath:String;

    public static const PROP_DESC_namePath:PropertyDesc = new PropertyDesc( "namePath" );
    public var namePath:String;

    public static const PROP_DESC_thumbnailWidth:PropertyDesc = new PropertyDesc( "thumbnailWidth" );
    public var thumbnailWidth:Number;

    public static const PROP_DESC_thumbnailHeight:PropertyDesc = new PropertyDesc( "thumbnailHeight" );
    public var thumbnailHeight:Number;

    public static const PROP_DESC_thumbnailFileName:PropertyDesc = new PropertyDesc( "thumbnailFileName" );
    public var thumbnailFileName:String;

    public static const PROP_DESC_indexedTime:PropertyDesc = new PropertyDesc( "indexedTime" );
    public var indexedTime:Date;

}
}