/**
 * Generated by com.customshow.codegen
 *
 */
package com.customshow.videotranscoding{

import mx.events.PropertyChangeEvent;
import com.flashflexpro.as3lib.data.PropertyDesc;
import flash.events.EventDispatcher;
import com.customshow.videotranscoding.DynaTableVideoTranscodingMediaInfo;
import org.apache.flex.collections.ArrayList;

[Bindable]
[RemoteClass(alias="com.customshow.videotranscoding.DynaTableVideoTranscoding")]
public class DynaTableVideoTranscoding extends EventDispatcher {
    public function DynaTableVideoTranscoding(){
    }

    private static var _allProperties:Vector.<PropertyDesc> = null;
    public static function get allProperties():Vector.<PropertyDesc>{
        if( _allProperties == null ){
            _allProperties = properties;
        }
        return _allProperties;
    }
    private static var _properties:Vector.<PropertyDesc> = null;
    public static function get properties():Vector.<PropertyDesc>{
        if( _properties == null ){
            _properties = new <PropertyDesc>[ PROP_DESC_version, 
                PROP_DESC_uploadBucketKey, 
                PROP_DESC_mediaId, 
                PROP_DESC_createTime, 
                PROP_DESC_lastUpdateTime, 
                PROP_DESC_status, 
                PROP_DESC_errorMsg, 
                PROP_DESC_mediaInfo, 
                PROP_DESC_formats
            ];
        }
        return _properties;
    }
    public static const PROP_DESC_version:PropertyDesc = new PropertyDesc( "version" );
    public var version:Number;

    public static const PROP_DESC_uploadBucketKey:PropertyDesc = new PropertyDesc( "uploadBucketKey" );
    public var uploadBucketKey:String;

    public static const PROP_DESC_mediaId:PropertyDesc = new PropertyDesc( "mediaId" );
    public var mediaId:String;

    public static const PROP_DESC_createTime:PropertyDesc = new PropertyDesc( "createTime" );
    public var createTime:Number;

    public static const PROP_DESC_lastUpdateTime:PropertyDesc = new PropertyDesc( "lastUpdateTime" );
    public var lastUpdateTime:Number;

    public static const PROP_DESC_status:PropertyDesc = new PropertyDesc( "status" , false, false, "", [ "Ready to process","Processing","Error","wrong_input","RETRY_421","Saved","Finished" ]);
    public var status:String;

    public static const PROP_DESC_errorMsg:PropertyDesc = new PropertyDesc( "errorMsg" );
    public var errorMsg:String;

    public static const PROP_DESC_mediaInfo:PropertyDesc = new PropertyDesc( "mediaInfo" );
    public var mediaInfo:DynaTableVideoTranscodingMediaInfo;

    public static const PROP_DESC_formats:PropertyDesc = new PropertyDesc( "formats" );
    public var formats:ArrayList;

}
}