/**
 * Generated by com.customshow.codegen
 *
 */
package com.customshow.videotranscoding{

import com.flashflexpro.as3lib.utils.RootContextModule;
import com.flashflexpro.as3lib.rpc.RpcSpringMvcPost;
import org.apache.flex.collections.ArrayList;
import com.flashflexpro.as3lib.rpc.RpcService;


//@see com.customshow.videotranscoding.TranscodingService
public class TranscodingService extends RpcService{
    public function TranscodingService( context:RootContextModule ){
        super( context );
    }

    public static const RPC_esLstByLastupdated:String = "esLstByLastupdated";
    public function esLstByLastupdated( result:Function, fault:Function, arg1:int, arg2:int, arg3:String, arg4:Boolean ):RpcSpringMvcPost{
        return createRpcPost( RPC_esLstByLastupdated, arguments );
    }

    public static const RPC_reEncodingJob:String = "reEncodingJob";
    public function reEncodingJob( result:Function, fault:Function, arg1:String ):RpcSpringMvcPost{
        return createRpcPost( RPC_reEncodingJob, arguments );
    }

    public static const RPC_addTranscoding:String = "addTranscoding";
    public function addTranscoding( result:Function, fault:Function, arg1:String, arg2:Number, arg3:org.apache.flex.collections.ArrayList ):RpcSpringMvcPost{
        return createRpcPost( RPC_addTranscoding, arguments );
    }

    public static const RPC_esLstByLastupdated11:String = "esLstByLastupdated11";
    public function esLstByLastupdated11( result:Function, fault:Function, arg1:int, arg2:int, arg3:String, arg4:Boolean ):RpcSpringMvcPost{
        return createRpcPost( RPC_esLstByLastupdated11, arguments );
    }

    public static const RPC_loadByStatusLastUpdateTime:String = "loadByStatusLastUpdateTime";
    public function loadByStatusLastUpdateTime( result:Function, fault:Function, arg1:String, arg2:Date, arg3:Number, arg4:Boolean ):RpcSpringMvcPost{
        return createRpcPost( RPC_loadByStatusLastUpdateTime, arguments );
    }

    public static const RPC_loadByBucketkeyCreateTime:String = "loadByBucketkeyCreateTime";
    public function loadByBucketkeyCreateTime( result:Function, fault:Function, arg1:String, arg2:Date, arg3:Number, arg4:Boolean ):RpcSpringMvcPost{
        return createRpcPost( RPC_loadByBucketkeyCreateTime, arguments );
    }

    public static const RPC_loadDestPreSignUrl:String = "loadDestPreSignUrl";
    public function loadDestPreSignUrl( result:Function, fault:Function, arg1:String, arg2:String ):RpcSpringMvcPost{
        return createRpcPost( RPC_loadDestPreSignUrl, arguments );
    }
}}