/**
 * Generated by com.customshow.codegen
 *
 */
package com.customshow.configPerClient{

import mx.events.PropertyChangeEvent;
import com.flashflexpro.as3lib.data.PropertyDesc;
import flash.events.EventDispatcher;
import com.customshow.configPerClient.DynaTableClientConfigTranscode;
import com.customshow.configPerClient.DynaTableClientConfigUpload;

[Bindable]
[RemoteClass(alias="com.customshow.configPerClient.DynaTableClientConfig")]
public class DynaTableClientConfig extends EventDispatcher {
    public function DynaTableClientConfig(){
    }

    private static var _allProperties:Vector.<PropertyDesc> = null;
    public static function get allProperties():Vector.<PropertyDesc>{
        if( _allProperties == null ){
            _allProperties = properties;
        }
        return _allProperties;
    }
    private static var _properties:Vector.<PropertyDesc> = null;
    public static function get properties():Vector.<PropertyDesc>{
        if( _properties == null ){
            _properties = new <PropertyDesc>[ PROP_DESC_clientId, 
                PROP_DESC_clientName, 
                PROP_DESC_initialTime, 
                PROP_DESC_lastModifyTime, 
                PROP_DESC_version, 
                PROP_DESC_transcode, 
                PROP_DESC_upload
            ];
        }
        return _properties;
    }
    public static const PROP_DESC_clientId:PropertyDesc = new PropertyDesc( "clientId" );
    public var clientId:String;

    public static const PROP_DESC_clientName:PropertyDesc = new PropertyDesc( "clientName" );
    public var clientName:String;

    public static const PROP_DESC_initialTime:PropertyDesc = new PropertyDesc( "initialTime" );
    public var initialTime:Number;

    public static const PROP_DESC_lastModifyTime:PropertyDesc = new PropertyDesc( "lastModifyTime" );
    public var lastModifyTime:Number;

    public static const PROP_DESC_version:PropertyDesc = new PropertyDesc( "version" );
    public var version:Number;

    public static const PROP_DESC_transcode:PropertyDesc = new PropertyDesc( "transcode" );
    public var transcode:DynaTableClientConfigTranscode;

    public static const PROP_DESC_upload:PropertyDesc = new PropertyDesc( "upload" );
    public var upload:DynaTableClientConfigUpload;

}
}