/**
 * Generated by com.customshow.codegen
 *
 */
package com.customshow.configPerClient{

import mx.events.PropertyChangeEvent;
import com.flashflexpro.as3lib.data.PropertyDesc;
import com.customshow.configPerClient.DynaTableClientConfigOverride;

[Bindable]
[RemoteClass(alias="com.customshow.configPerClient.DynaTableClientConfigTranscode")]
public class DynaTableClientConfigTranscode extends com.customshow.configPerClient.DynaTableClientConfigOverride {
    public function DynaTableClientConfigTranscode(){
    }

    private static var _allProperties:Vector.<PropertyDesc> = null;
    public static function get allProperties():Vector.<PropertyDesc>{
        if( _allProperties == null ){
            _allProperties = properties.concat( com.customshow.configPerClient.DynaTableClientConfigOverride.allProperties );
        }
        return _allProperties;
    }
    private static var _properties:Vector.<PropertyDesc> = null;
    public static function get properties():Vector.<PropertyDesc>{
        if( _properties == null ){
            _properties = new <PropertyDesc>[ PROP_DESC_autoStartOnUploaded, 
                PROP_DESC_s3UploadReadAuthExpireDelayInSecs, 
                PROP_DESC_s3DownloadWriteAuthExpireDelayInSecs, 
                PROP_DESC_maxVideoFormatsNum, 
                PROP_DESC_maxThumbFormatsNum, 
                PROP_DESC_formats
            ];
        }
        return _properties;
    }
    public static const PROP_DESC_autoStartOnUploaded:PropertyDesc = new PropertyDesc( "autoStartOnUploaded" );
    public var autoStartOnUploaded:Boolean;

    public static const PROP_DESC_s3UploadReadAuthExpireDelayInSecs:PropertyDesc = new PropertyDesc( "s3UploadReadAuthExpireDelayInSecs" );
    public var s3UploadReadAuthExpireDelayInSecs:Number;

    public static const PROP_DESC_s3DownloadWriteAuthExpireDelayInSecs:PropertyDesc = new PropertyDesc( "s3DownloadWriteAuthExpireDelayInSecs" );
    public var s3DownloadWriteAuthExpireDelayInSecs:Number;

    public static const PROP_DESC_maxVideoFormatsNum:PropertyDesc = new PropertyDesc( "maxVideoFormatsNum" );
    public var maxVideoFormatsNum:int;

    public static const PROP_DESC_maxThumbFormatsNum:PropertyDesc = new PropertyDesc( "maxThumbFormatsNum" );
    public var maxThumbFormatsNum:int;

    public static const PROP_DESC_formats:PropertyDesc = new PropertyDesc( "formats" );
    public var formats:Object;

}
}